#ifndef SYS_STACKS_H
#define SYS_STACKS_H

#include "types.h"

#if defined(TARGET_PC)
#define PC_STACK_GUARD_SIZE 0x1000
#define IRQMGR_STACK_USABLE_SIZE 0x1000
#define PADMGR_STACK_USABLE_SIZE 0x1000
#define GRAPH_STACK_USABLE_SIZE 0x10000
#define IRQMGR_STACK_SIZE (IRQMGR_STACK_USABLE_SIZE + PC_STACK_GUARD_SIZE)
#define PADMGR_STACK_SIZE (PADMGR_STACK_USABLE_SIZE + PC_STACK_GUARD_SIZE)
#define GRAPH_STACK_SIZE (GRAPH_STACK_USABLE_SIZE + PC_STACK_GUARD_SIZE)
#else
#define IRQMGR_STACK_SIZE 0x1000
#define PADMGR_STACK_SIZE 0x1000
#define GRAPH_STACK_SIZE 0x2000
#endif

extern u8 graphStack[];
extern u8 padmgrStack[];
extern u8 irqmgrStack[];



#endif